### ISSUE TITLE
Pan or zoom does not work in Firefox

### ISSUE THREAD

**Issue by magjac** [magjac/graphviz-visual-editor#124]
In v0.6.1 pan or zoom of the graph does not work in Firefox 71. It works in Chrome though.

**Comment by magjac** [comment]
It *does* work also in Firefox. It was just something fishy with my computer when I wrote this issue.

**Comment by Zian** [comment]
I had the same problem. I noticed that the Firefox Developer Tools showed an error & call stack in the Console before I clicked in the graph area.

The next time the issue happens, I'll try to provide that information.
