### ISSUE TITLE
Can graphviz-visual-editor accept images?

### ISSUE THREAD

**Issue by dragonauta** [magjac/graphviz-visual-editor#145]
Using dot files, you can add
> imgnode[image="apple-touch-icon.png", label=""];

to show a png.
Has graphviz-visual-editor this ability?

**Comment by magjac** [comment]
Sorry, no it hasn't. But I guess it could be implemented through d3-graphviz [addImage()](https://github.com/magjac/d3-graphviz#graphviz_addImage).

**Comment by dragonauta** [comment]
No problem. Kudos. graphviz-visual-editor is a great tool and I can build my dot graph file and then replace nodes with desired images. An extra step, but results are just great.
