### ISSUE TITLE
Unhandled Rejection (RuntimeError): abort(CompileError: WebAssembly.instantiate(): expected magic word

### ISSUE THREAD

**Issue by ohad1989** [magjac/graphviz-visual-editor#153]
Hi,
I'm trying to run the application. I ran the suggested command:
```
git clone https://github.com/magjac/graphviz-visual-editor
cd graphviz-visual-editor
npm install
make
npm run start
```
Now, just right after the application appears for a few milliseconds, it crashes and I get this error:
Unhandled Rejection (RuntimeError): abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 2e 2e 2f 2e @+0). Build with -s ASSERTIONS=1 for more info.
abort
C:/.../build/graphviz/graphvizlib/graphvizlib.js:9

I tried cp -p node_modules/@hpcc-js/wasm/dist/graphvizlib.wasm public/js as suggested [here](https://github.com/magjac/d3-graphviz/issues/152) without help.

Thanks in advance!

**Comment by ohad1989** [comment]
It was fixed by copying all the directory to the public directory, and not only graphvizlib.wasm

**Comment by zoharit** [comment]
Hi , 
i got the same issue 
Thanks

**Comment by magjac** [comment]
Is this still a problem? @ohad1989 @zoharit You both seem to have deleted your comments.

> C:/.../build/graphviz/graphvizlib/graphvizlib.js:9

This suggests to me that you're running this on Windows. The repo contains a symbolic link: https://github.com/magjac/graphviz-visual-editor/blob/master/%40hpcc-js that probable doesn't work on Windows. Also, the Makefile is not built to run on Windows, so I'm kind of surprised you even managed to build it.

**Comment by ohad1989** [comment]
Hi, Thanks for your comment. 
make did work with some warnings. 
In general, it worked after copying the whole folder (kind of a WA instead of using a symbolic link).
