### ISSUE TITLE
Exporting images

### ISSUE THREAD

**Issue by jamesrenxiangyu** [magjac/graphviz-visual-editor#159]
Hi! great works!
I am wondering if I can directly export the image in .pdf format, or if the DOT code can be used in latex or overleaf ? I tried to use the code directly in overleaf but failed. I am wondering if there needs any packages?
Thanks!

**Comment by magjac** [comment]
Sorry for the delay. No, currently PDF is not supported.

I don't know what overleaf is or how you would use the code directly in it. What did you try to do and what errors did you get?

**Comment by jamesrenxiangyu** [comment]
Thanks for replying! 
Overleaf is an online LaTex editor. I tried to director use the DOT in LaTex to generate the corresponding flow graphs but failed. I later realized DOT language is not supported in LaTex, which causes errors when generating the PDF file. Anyways, graphviz is always a handy tool to use! Great work!
