### ISSUE TITLE
Can't resolve './dotParser'

### ISSUE THREAD

**Issue by osequi** [magjac/graphviz-visual-editor#162]
Hello,

Just cloned the repo, issued `yarn start` and got this error message:

```
Failed to compile.

./src/dot.js
Module not found: Can't resolve './dotParser' in '/home/cs/osequi/graphviz-visual-editor/src'
```

Thanks :)

**Comment by magjac** [comment]
Please see https://github.com/magjac/graphviz-visual-editor#installation

**Comment by osequi** [comment]
Oh, sorry :)
