### ISSUE TITLE
Mrecord used with rank=same

### ISSUE THREAD

**Issue by fzzylogic** [magjac/graphviz-visual-editor#163]
Great tool, thanks for sharing it!

Here's something i noticed. Using "record" or "Mrecord" and rank=same, no edge is rendered between nodes. The correct shape is drawn though. For polygon based shapes the edge is present in the rendered svg, but missing for record type shapes.

```
digraph {
    node [shape=Mrecord]
    a -> b
    {rank=same a b}
}
```

Thank you

**Comment by magjac** [comment]
Sorry for the delay.

This seems to be a bug in Graphviz itself. Please file a bug at https://gitlab.com/graphviz/graphviz/-/issues/new.
