### ISSUE TITLE
Save to "browser's local storage"?

### ISSUE THREAD

**Issue by silverwoodchuck47** [magjac/graphviz-visual-editor#164]
That's a terrible place to put a file. Where is "browser's local storage"?  Why do I have to hunt for that location?

Treat the output as a file and let the browser download it to wherever the user prefers.

![image](https://user-images.githubusercontent.com/14035865/117061732-89dca780-acf0-11eb-964c-e48c9cb02cd1.png)

**Comment by magjac** [comment]
See https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage. It's a very convenient way of always having the  graph *DOT source code* stored without any risk that the user looses it when they leave the page.

If you're building the application yourself, you can use the [unreleased](https://github.com/magjac/graphviz-visual-editor/blob/master/CHANGELOG.md#unreleased) "Export as SVG" function to export the rendered graph in the SVG format to your file system.

Save and load of the DOT source code is described in this [enhancement request](https://github.com/magjac/graphviz-visual-editor/issues/81), but is not yet implemented.
