### ISSUE TITLE
No arrow sign if rank=same between elements

### ISSUE THREAD

**Issue by laszlojanosek** [magjac/graphviz-visual-editor#179]
Trying to achieve a diagram in which horizontal and vertical relations of elements are changing. If I use "rank=same" between components, the horizontal arrow between these is not drawn.
Using a different application, I see the arrows.

The code:
```
strict digraph {
    BPR [label="Backup Prerquisites" shape="Mrecord" style="rounded,filled" fillcolor="#3a9129" fontcolor="white"]
    UCF [label="Update Config Files" shape="Mrecord" style="rounded,filled" fillcolor="#3a9129" fontcolor="white"]
    DCL [label="Data Collection" shape="Mrecord" style="rounded,filled" fillcolor="#3a9129" fontcolor="white"]
    FBP [label="FS Backup Preparation" shape="Mrecord" style="rounded,filled" fillcolor="#1f629d" fontcolor="white"]
    DDB [label="DSS Database Backup" shape="Mrecord" style="rounded,filled" fillcolor="#1f629d" fontcolor="white"]
    FSB [label="FS Backup" shape="Mrecord" style="rounded,filled" fillcolor="#1f629d" fontcolor="white"]
    BPR -> UCF -> DCL
    DCL -> FBP
    FBP -> DDB -> FSB
    {rank= same; DCL; FBP;}
    {rank= same; DDB; FSB;}
}
```

Rendered with Graphviz Visual Editor:

![Screenshot 2021-12-01 101430](https://user-images.githubusercontent.com/43501165/144205952-9ed6fad5-b651-40eb-bc3b-a5e4538777ae.png)

Rendered on http://graphviz.it/

![Screenshot 2021-12-01 101529](https://user-images.githubusercontent.com/43501165/144206090-4918a598-b4eb-4e6d-af07-1594d340116e.png)

**Comment by magjac** [comment]
Thanks for using the editor and for reporting this issue. I think however, that this is a problem with [Graphviz](https://graphviz.org/) itself:
```
$ dot gve-issue-179.dot -Tsvg  > tmp.svg
Warning: flat edge between adjacent nodes one of which has a record shape - replace records with HTML-like labels
  Edge DDB -> FSB
Error: lost DCL FBP edge
Error: lost DDB FSB edge
$ dot -V
dot - graphviz version 2.49.4~dev.20211204.0711 (20211204.0711)
```
You may want to open an issue at https://gitlab.com/graphviz/graphviz/-/issues or ask for help at https://forum.graphviz.org/c/help/5.
