### ISSUE TITLE
Module not found: Can't resolve './dotParser' 

### ISSUE THREAD

**Issue by kasra0** [magjac/graphviz-visual-editor#183]
Hi, 

I cloned the repo  then 
npm run start 
or
npm run start:coverage 
and I got  : 

Failed to compile
./src/dot.js
Module not found: Can't resolve './dotParser' in '...\graphviz-visual-editor\src'

Am I missing something ?

thanks

**Comment by magjac** [comment]
Yes. See the [installation instructions](https://github.com/magjac/graphviz-visual-editor#installation).

**Comment by kasra0** [comment]
forgot to make... indeed.

after **npm run start**  it compiled successfully 

but I got  a runtime error . From the browser console  :

:3000/@hpcc-js/wasm/dist/index.min.js:1 Uncaught SyntaxError: Unexpected token '.'
    at self.onmessage (f9995c32-143e-489b-a111-15e0e4b67f5d:8)
graphvizlib.js:9 Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 2e 2e 2f 2e @+0). Build with -s ASSERTIONS=1 for more info.
    at abort (graphvizlib.js:9)
    at graphvizlib.js:9

I am not at all aware about WebAssembly.
Do you have any clue ?

I am on windows 10
node version  v16.13.1

**Comment by magjac** [comment]
I have only used it on Linux. I suspect that it doesn't work on Windows. There is a symbolic link in the repo. I don't know how Windows handles that. Perhaps you can find a way to work around it. Perhaps by just making a copy instead.

```
$ file @hpcc-js
@hpcc-js: symbolic link to public/@hpcc-js
```

**Comment by kasra0** [comment]
Thanks ! that was the problem

I just copied the files 

- graphvizlib.wasm
- index.min.js
from :
**graphviz-visual-editor\node_modules\@hpcc-js\wasm\dist**
into:
**graphviz-visual-editor\public\@hpcc-js\wasm\dist**

and it worked.

Hope that it will help the future windows guys
