### ISSUE TITLE
Cypress 4.5.0 no longer available

### ISSUE THREAD

**Issue by gdudek** [magjac/graphviz-visual-editor#189]
The desired cypress 4.5.0 is not available. as it's now at 9.4.1, but a simple:
  npm install cypress
should work.

[ This may be a bogus issue due to my ancient npm system. If so, sorry. ]

**Comment by magjac** [comment]
There no problem to use 4.5.0 in [CI](https://app.circleci.com/pipelines/github/magjac/graphviz-visual-editor/277/workflows/9ce9a3d3-d5bc-41fd-b6fe-d668c75c5c28/jobs/508).

That said, I'm in the process of upgrading all dependencies and I'll get to Cypress in due time as well. I tried to do a full npm update, but [CI failed](https://app.circleci.com/pipelines/github/magjac/graphviz-visual-editor/268/workflows/6c35f08c-2928-4a20-a34c-9d5799b68d27/jobs/490) so I'm doing them one by one.
