### ISSUE TITLE
Confirm making "new" graph

### ISSUE THREAD

**Issue by sneakers-the-rat** [magjac/graphviz-visual-editor#204]
Hello! Thanks for making this tool, it's been very useful!

I just lost a decent amount of work by accidentally clicking the "new" button thinking it was the "insert" button, and it doesn't seem like there's a way to restore it. I think it needs a confirmation dialogue! "Are you sure you want to make a new graph? The current graph will be lost! (Y/N)" 

I can draft a quick PR if you're busy :)

**Comment by magjac** [comment]
Thanks for the report. However, your work probably isn't lost. When you click the "new" button, the old graph is saved in your browser's local storage. You can retrieve it with the 
![image](https://user-images.githubusercontent.com/6350376/162067516-f56b3759-8fda-4b7e-8c52-c999a081a8c5.png)
button or from the menu alternative **Open from browser**:
![image](https://user-images.githubusercontent.com/6350376/162067670-e56bf3eb-6cdd-4aed-adf7-186e1ae0f0ed.png)
which should open a menu like this:
![image](https://user-images.githubusercontent.com/6350376/162067773-1a2a8c47-191d-4b3a-98ca-faa72ef2ff21.png)

If this for some reason doesn't work for you, please let me know and I will look into it.

**Comment by sneakers-the-rat** [comment]
omg amazing. thanks! a little popup reminder would be nice, I went and remade the whole thing before I saw this!
