### ISSUE TITLE
New Nodes Created After Linking Nodes With a Space in the Label

### ISSUE THREAD

**Issue by Zian** [magjac/graphviz-visual-editor#215]
After I link together two nodes together using my mouse, many new nodes are unexpectedly created if one of the two nodes has more than 1 word in it.

Steps to Reproduce:
1. Go to http://magjac.com/graphviz-visual-editor/.
2. Paste the following text into the left side of the window:
```
strict digraph {
    Delta
    "Dallas Fort Worth International Airport"
}
```
3. Right-click on the "Delta" node in the right half of the screen.
4. Double-click on the "Dallas Fort Worth International Airport" node with the left mouse button.

Expected Result:
The Delta node and the "Dallas Fort Worth International Airport" node should be connected with an arrow.

Actual Result:
- A new node called "Dallas" is created and connected to the "Delta" node.
- Additional nodes are created:
  - Fort
  - Worth
  - International
  - Airport

System Information:
- Firefox 105.0.3
- Windows 10 Version 21H2

**Comment by magjac** [comment]
Thanks for the report. I can confirm that this is a bug. I will look into it, but not in the near future I'm afraid.

**Comment by Zian** [comment]
The problem no longer occurs. Thank you, ygra and magjac, for fixing the issue.
