### ISSUE TITLE
Edges to grouped nodes not working (curly braces)

### ISSUE THREAD

**Issue by mcp292** [magjac/graphviz-visual-editor#232]
```graphviz
digraph mwe {
  works -> {yes, no}
}
```

[Edit in playground](http://magjac.com/graphviz-visual-editor/?dot=digraph%20mwe%20%7B%0A%20%20works%20-%3E%20%7Byes%2C%20no%7D%0A%7D%0A).

**Comment by magjac** [comment]
Comma is not a valid separator in the [DOT language](https://graphviz.org/doc/info/lang.html). Remove it or use a semicolon instead.
