### ISSUE TITLE
Bug: The input is error when typing quickly

### ISSUE THREAD

**Issue by Honghe** [magjac/graphviz-visual-editor#236]
Below gif is the replay (2x times slower typing speed), i.e. the `l` letter is lost.
![magjac_bug3](https://github.com/magjac/graphviz-visual-editor/assets/1092722/d789d48a-40fc-4767-b978-e79b48650a86)

**Comment by magjac** [comment]
Thanks for the report. I've seen this myself too.

You might be able to avoid this problem most of the times, by setting the hold-off time to something like one second in the settings:

![image](https://github.com/magjac/graphviz-visual-editor/assets/6350376/c52702cc-cd64-4f96-8323-e2bef78b4b48)

I've struggled with similar bugs in the past:

- https://github.com/magjac/graphviz-visual-editor/issues/22
- https://github.com/magjac/graphviz-visual-editor/issues/99

This seems to be yet another flavor :weary: .

**Comment by magjac** [comment]
Some debugging shows that this is the same problem as https://github.com/magjac/graphviz-visual-editor/issues/22.

Five years ago, I seem to have been aware of that this problem was not entirely fixed. See https://github.com/magjac/graphviz-visual-editor/issues/22#issuecomment-416827934.
