### ISSUE TITLE
Please add the ability to see the dot command

### ISSUE THREAD

**Issue by kasra0** [magjac/graphviz-visual-editor#271]
Hi,

It's not an issue, more a wanted feature...
It would be great to have the command that produced the output ( what we see ).
I don't know if it's easily implementable, but if it is, it has great educational value.

Thanks

**Comment by magjac** [comment]
Thanks for the suggestion. Unfortunately there is never any command that runs, since Graphviz is used as a library (translated to JavaScript), but an equivalent command would be:

```
dot -Tsvg input.dot -o output.svg
```

**Comment by kasra0** [comment]
yes, I noticed after my post.
Thanks
