### ISSUE TITLE
NetworkX integration

### ISSUE THREAD

**Issue by hingehe** [magjac/graphviz-visual-editor#98]
I am working with a python package called NetworkX:
https://networkx.github.io/

It is awesome for my backend purposes building graphs and relationships, but offers (if any) only rediclueless visualization tools. So I've written a small piece of python code, which takes a NetworkX graph object and creates a DOT txt file for your visual editor, ready to be pasted in there. I use it for debuggen and dev of my backend algorithms. If you are interested, I could contribute this somehow...

**Comment by hingehe** [comment]
Hi magjac. I haven't found another way to contact you, so I open a ticket. Feel free to delete it!

**Comment by magjac** [comment]
I have a Slack workspace set up for Graphviz related stuff:

https://join.slack.com/t/d3-graphviz/shared_invite/enQtMzMwODQzMDI5MDA5LTExYTgyYThhNzI3YjJlODRiMzQ3MWM3YWI5ZjAyMTI2MmI4YWIwMDM4ZmY5MDQzNjkzMDY4YTRmMTU1YzIzNTY

After logging in, you can use the **#graphviz-viz-editor** channel.

Let's continue the discussion there.
